# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4c7c1c9f1fddd21b471226fedb02a0c6"
application_url = "https://waiver-aruba-badly-inserted.trycloudflare.com"
embedded = true
name = "Vi-Shop"
handle = "vi-shop-2"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://waiver-aruba-badly-inserted.trycloudflare.com/auth/callback",
  "https://waiver-aruba-badly-inserted.trycloudflare.com/auth/shopify/callback",
  "https://waiver-aruba-badly-inserted.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
